name: deploy_win
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check windows-x86_64-devel
      env:
        DOCKER_LOGIN_TOKEN: ${{ secrets.DOCKER_LOGIN_TOKEN }}
        LANGSERVERSETUP_RUN_DEPLOY: true
      run: sh inst/docker_stage.sh inst/check_rhub.R "windows-x86_64-devel"
